export const careers = [
  // --- Programming & Software Development ---
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile App Developer",
  "React Developer",
  "Next.js Developer",
  "Node.js Developer",
  "DevOps Engineer",
  "Software Engineer",
  "Web Developer",
  "Cloud Engineer",
  "Systems Engineer",
  "Embedded Systems Developer",
  "Game Developer",
  "Desktop Application Developer",
  "Data Engineer",
  "Database Administrator",
  "Site Reliability Engineer (SRE)",
  "Machine Learning Engineer",
  "AI Engineer",
  "Computer Vision Engineer",
  "NLP Engineer",
  "Automation Engineer",

  // --- Data, AI & Analytics ---
  "Data Analyst",
  "Business Analyst",
  "Data Scientist",
  "Deep Learning Specialist",
  "Big Data Engineer",
  "ETL Developer",
  "BI Analyst",
  "Statistician",
  "Quantitative Analyst (Quant)",
  "Data Visualization Specialist",

  // --- Cloud, DevOps & Infra ---
  "Cloud Architect",
  "AWS Engineer",
  "Azure Engineer",
  "GCP Engineer",
  "Kubernetes Administrator",
  "CI/CD Engineer",
  "Infrastructure Engineer",
  "Monitoring & Observability Engineer",
  "Cloud Security Engineer",

  // --- Cybersecurity ---
  "Cybersecurity Analyst",
  "Penetration Tester",
  "Ethical Hacker",
  "Security Engineer",
  "SOC Analyst",
  "Incident Response Specialist",
  "Vulnerability Analyst",
  "Information Security Manager",

  // --- Design & Creative ---
  "UI/UX Designer",
  "Product Designer",
  "Graphic Designer",
  "Brand Designer",
  "Motion Designer",
  "Animator",
  "Video Editor",
  "3D Artist",
  "Illustrator",
  "Creative Director",
  "Web Designer",

  // --- Marketing & SEO ---
  "Digital Marketer",
  "SEO Specialist",
  "Content Marketer",
  "Social Media Manager",
  "SEM Specialist",
  "Performance Marketer",
  "Email Marketing Specialist",
  "Affiliate Marketing Manager",
  "Growth Marketer",
  "Marketing Analyst",

  // --- Business & Management ---
  "Project Manager",
  "Scrum Master",
  "Product Manager",
  "Operations Manager",
  "Business Development Manager",
  "Strategic Planner",
  "Team Lead",
  "Program Manager",
  "Process Improvement Specialist",
  "Customer Success Manager",

  // --- Finance & Accounting ---
  "Accountant",
  "Financial Analyst",
  "Investment Analyst",
  "Auditor",
  "Tax Specialist",
  "Payroll Specialist",
  "Bookkeeper",
  "Financial Planner",

  // --- Writing, Communication & Education ---
  "Technical Writer",
  "Copywriter",
  "Editor",
  "Content Writer",
  "Researcher",
  "Public Speaker",
  "Presentation Specialist",
  "Teacher",
  "Instructor",
  "Corporate Trainer",
  "Curriculum Designer",

  // --- HR & Recruiting ---
  "HR Manager",
  "Recruiter",
  "Talent Acquisition Specialist",
  "HR Coordinator",
  "Learning & Development Specialist",
  "HR Analyst",

  // --- Sales & Customer Support ---
  "Sales Representative",
  "Account Manager",
  "Sales Executive",
  "Business Development Executive",
  "Customer Support Specialist",
  "Customer Experience Manager",
  "Lead Generation Specialist",

  // --- Healthcare & Science ---
  "Healthcare Manager",
  "Clinical Research Assistant",
  "Medical Coder",
  "Public Health Analyst",
  "Biotech Analyst",

  // --- Supply Chain, Logistics & Operations ---
  "Supply Chain Specialist",
  "Logistics Coordinator",
  "Procurement Officer",
  "Quality Assurance Specialist",
  "Manufacturing Coordinator",

  // --- Legal, Language & Other ---
  "Legal Researcher",
  "Translator",
  "Interpreter",
  "Event Planner",
  "Product Coordinator",
  "Problem-Solving Specialist",
  "Strategy Consultant",
];
