// constants/skills.ts

export const skills = [
  // --- Programming & Development ---
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "Go",
  "PHP",
  "Ruby",
  "Swift",
  "Kotlin",
  "Rust",
  "Dart",
  "SQL",
  "NoSQL",
  "HTML",
  "CSS",
  "React",
  "Next.js",
  "Vue.js",
  "Angular",
  "Node.js",
  "Express.js",
  "NestJS",
  "Django",
  "Flask",
  "FastAPI",
  "Spring Boot",
  "Laravel",
  "ASP.NET",
  "GraphQL",
  "REST API",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud Platform (GCP)",
  "Firebase",
  "Supabase",
  "PostgreSQL",
  "MongoDB",
  "MySQL",
  "Redis",
  "SQLite",
  "Prisma",
  "Drizzle ORM",
  "Git",
  "GitHub",
  "GitLab",
  "CI/CD",
  "Linux",
  "Bash",
  "Shell Scripting",
  "WebSockets",
  "WebRTC",
  "Electron",
  "Expo",
  "React Native",
  "Flutter",
  "Ionic",
  "Tailwind CSS",
  "Bootstrap",
  "Material UI",
  "Shadcn UI",
  "Vite",
  "Webpack",
  "Bun",
  "Turborepo",

  // --- Data & AI ---
  "Data Analysis",
  "Data Visualization",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "Seaborn",
  "Excel",
  "Power BI",
  "Tableau",
  "Machine Learning",
  "Deep Learning",
  "TensorFlow",
  "Keras",
  "PyTorch",
  "Scikit-learn",
  "Computer Vision",
  "NLP",
  "Chatbot Development",
  "LangChain",
  "OpenAI API",
  "Data Mining",
  "Big Data",
  "Apache Spark",
  "Hadoop",
  "ETL",
  "Data Engineering",
  "Data Warehousing",
  "SQL Optimization",
  "Statistics",
  "R Programming",

  // --- Design & Creative ---
  "UI/UX Design",
  "Figma",
  "Adobe XD",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Canva",
  "Sketch",
  "InVision",
  "Wireframing",
  "Prototyping",
  "Graphic Design",
  "Logo Design",
  "Brand Identity",
  "Animation",
  "Video Editing",
  "Adobe Premiere Pro",
  "After Effects",
  "3D Design",
  "Blender",
  "Motion Graphics",

  // --- Marketing & SEO ---
  "Digital Marketing",
  "Social Media Marketing",
  "Search Engine Optimization (SEO)",
  "Search Engine Marketing (SEM)",
  "Content Marketing",
  "Email Marketing",
  "Affiliate Marketing",
  "Google Ads",
  "Facebook Ads",
  "Google Analytics",
  "Content Strategy",
  "Influencer Marketing",
  "Brand Management",
  "Market Research",
  "E-commerce Marketing",

  // --- Business & Management ---
  "Project Management",
  "Agile Methodology",
  "Scrum",
  "Kanban",
  "Jira",
  "Trello",
  "Asana",
  "Notion",
  "Slack",
  "Leadership",
  "Strategic Planning",
  "Operations Management",
  "Business Analysis",
  "Change Management",
  "Process Improvement",
  "Customer Relationship Management (CRM)",
  "Negotiation",
  "Risk Management",
  "Time Management",
  "Team Building",
  "Budgeting",

  // --- Finance & Accounting ---
  "Financial Analysis",
  "Accounting",
  "Bookkeeping",
  "QuickBooks",
  "Microsoft Excel (Advanced)",
  "Forecasting",
  "Auditing",
  "Taxation",
  "Payroll Management",
  "Investment Analysis",

  // --- Writing & Communication ---
  "Technical Writing",
  "Creative Writing",
  "Business Writing",
  "Copywriting",
  "Editing",
  "Proofreading",
  "Research",
  "Public Speaking",
  "Presentation Skills",
  "Communication Skills",
  "Storytelling",

  // --- HR & Recruiting ---
  "Recruitment",
  "Talent Acquisition",
  "Onboarding",
  "HR Management",
  "Performance Management",
  "Employee Engagement",
  "Compensation & Benefits",
  "Workforce Planning",
  "HR Analytics",
  "Training & Development",

  // --- Sales & Customer Support ---
  "Sales Strategy",
  "B2B Sales",
  "B2C Sales",
  "Cold Calling",
  "Lead Generation",
  "Customer Service",
  "CRM Tools",
  "Salesforce",
  "HubSpot",
  "Customer Retention",
  "Upselling",
  "Account Management",

  // --- Cybersecurity & IT ---
  "Cybersecurity",
  "Ethical Hacking",
  "Penetration Testing",
  "Network Security",
  "Information Security",
  "DevSecOps",
  "Incident Response",
  "Risk Assessment",
  "Firewall Management",
  "Vulnerability Assessment",
  "SIEM Tools",
  "Endpoint Security",

  // --- DevOps & Cloud Infrastructure ---
  "DevOps",
  "CI/CD Pipelines",
  "Terraform",
  "Ansible",
  "Jenkins",
  "GitHub Actions",
  "Kubernetes Administration",
  "Containerization",
  "Monitoring & Logging",
  "Prometheus",
  "Grafana",
  "Cloud Security",
  "Serverless Architecture",

  // --- Education & Training ---
  "Teaching",
  "Curriculum Design",
  "Instructional Design",
  "E-learning Development",
  "Classroom Management",
  "Mentorship",
  "Training Delivery",
  "Learning Management Systems (LMS)",

  // --- Healthcare & Science ---
  "Healthcare Management",
  "Medical Coding",
  "Clinical Research",
  "Pharmacology",
  "Patient Care",
  "Laboratory Analysis",
  "Public Health",
  "Biotechnology",
  "Data Science for Healthcare",

  // --- Other Industry Skills ---
  "Supply Chain Management",
  "Logistics",
  "Procurement",
  "Manufacturing Processes",
  "Quality Assurance",
  "Customer Experience (CX)",
  "Product Management",
  "Product Design",
  "Event Planning",
  "Legal Research",
  "Contract Management",
  "Translation",
  "Foreign Languages",
  "Problem Solving",
  "Critical Thinking",
  "Adaptability",
  "Creativity",
  "Team Collaboration",
];
